---
- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present

- name: Add Elasticsearch apt key.
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Kibana repository.
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/{{ kibana_release }}/apt stable main'
    state: present
    update_cache: true

- name: Get installed kibana version
  command: dpkg-query --showformat='${Version}' --show {{ kibana_package }}
  register: installed_kibana_version
  failed_when: False
  changed_when: False
  check_mode: no

- name: Unhold kibana version
  dpkg_selections:
    name: "{{ kibana_package }}"
    selection: "install"
  when: not kibana_version_lock or (installed_kibana_version.stdout and installed_kibana_version.stdout != kibana_version)

- name: Version separator
  set_fact: version_separator="="
